/**
 * The Catchmon roster. Everything about a species lives here: how it looks,
 * how it behaves, how hard it is to catch and what it is worth.
 *
 * `weight` is the base spawn weight; `lateWeight` is the weight it drifts
 * towards by the end of a round, so rare mons show up when the heat is on.
 */
export const SPECIES = [
  {
    id: 'sproutle',
    name: 'Sproutle',
    crest: 'leaf',
    rarity: 1,
    color: '#9ce87a',
    accent: '#3f8f2b',
    belly: '#d7f2b8',
    radius: 24,
    speed: 52,
    catchRate: 0.74,
    points: 100,
    weight: 46,
    lateWeight: 20,
  },
  {
    id: 'emberkit',
    name: 'Emberkit',
    crest: 'flame',
    rarity: 2,
    color: '#ffa94d',
    accent: '#d35400',
    belly: '#ffd9a8',
    radius: 23,
    speed: 74,
    catchRate: 0.58,
    points: 190,
    weight: 22,
    lateWeight: 22,
  },
  {
    id: 'dripso',
    name: 'Dripso',
    crest: 'drop',
    rarity: 2,
    color: '#5cc9f5',
    accent: '#0277bd',
    belly: '#cdeeff',
    radius: 22,
    speed: 80,
    catchRate: 0.55,
    points: 210,
    weight: 20,
    lateWeight: 20,
  },
  {
    id: 'zapling',
    name: 'Zapling',
    crest: 'bolt',
    rarity: 3,
    color: '#ffe066',
    accent: '#e0a800',
    belly: '#fff6cc',
    radius: 20,
    speed: 118,
    catchRate: 0.42,
    points: 340,
    weight: 9,
    lateWeight: 20,
  },
  {
    id: 'umbrix',
    name: 'Umbrix',
    crest: 'horns',
    rarity: 4,
    color: '#a678de',
    accent: '#4c2a72',
    belly: '#d9c4f2',
    radius: 21,
    speed: 132,
    catchRate: 0.3,
    points: 560,
    weight: 2.6,
    lateWeight: 12,
  },
  {
    id: 'prismon',
    name: 'Prismon',
    crest: 'star',
    rarity: 5,
    color: '#ff7bd5',
    accent: '#a4179c',
    belly: '#ffd6f2',
    radius: 19,
    speed: 152,
    catchRate: 0.19,
    points: 1200,
    weight: 0.4,
    lateWeight: 6,
  },
];

export const SPECIES_BY_ID = new Map(SPECIES.map((species) => [species.id, species]));
